### ISSUE TITLE
ImageReferences

### ISSUE THREAD

**Issue by AeroNotix** [AeroNotix/hpcloud#1]
@technosophos informed me that the ImageReferences in https://github.com/AeroNotix/hpcloud/blob/master/compute.go#L59 are volatile.

However, I'm not sure how to combat the ever-changing list of them.

We could:
- Query them and populate a map[string]string of available images in an init() function.
- Remove the constants altogether (well, I will remove const, for sure) and have people just pass raw ID's to the CreateServer call.

How would you like to see this done?

I will :
- ~~Implement the ListImages endpoint~~ DONE
- ~~Remove const from the ImageRef instances and go to var so you can change them in client-side code (stop-gap)~~ DONE

**Comment by AeroNotix** [comment]
compute.Images could have a method: ChooseImage(distro,bitsize) => ImageRef ?

**Comment by technosophos** [comment]
I think it's also possible to get a deprecation flag (whether or not an image has been deprecated). That is actually useful.

ChooseImage(distro string, bitsize int, includeDeprecated boolean) => []ImageRef 

(Or maybe that should be a separate function)

**Comment by AeroNotix** [comment]
Cool. I like this idea. I'll implement this tomorrow and stick it in a feature branch or something. (Pull requests welcome if anyone else gets a chance)

**Comment by AeroNotix** [comment]
Whilst I am implementing Erlang bindings I'm again coming up against this problem, I'm not sure of a single solution to this and any input is appreciated. The solution provided for by technosophos is a pretty good one and I am yet to implement it. It's the best idea so far.

However, it requires that the images have somewhat parsable naming conventions. Not to mention either parsing them at either login time (I prefer this option) or parsing them at  ChooseImage time (not a fan of this way since it has extra over head just for choosing an image). The parsing is mostly ok at the moment so I am not very apprehensive about that.

/cc @mattfarina @gorah for input

**Comment by technosophos** [comment]
I know that the MC team seems to have access to a more structured set of info on images, but I don't know where they are getting it.

**Comment by AeroNotix** [comment]
MC team?

**Comment by technosophos** [comment]
Oh, sorry... lapsed into jargon automatically. The team that does the HP Cloud management console.

**Comment by AeroNotix** [comment]
If you could ask them how they're doing it, it'd be a massive help. If they're using the API then they must have some faith in the stability in it. If not, then it means that I can't reliably provide a service for that and thus am able to have runtime checks of the images. Which is also fine.

**Comment by technosophos** [comment]
I guess they are using a mish-mash of public APIs and internal (non-public)
stuff. For much of it, they use the HPFog Ruby bindings. This seems to be
the definitive API documentation:
http://docs.hpcloud.com/bindings/fog/compute#ModelImageOperations-jumplink-span

On Fri, Jun 7, 2013 at 3:14 PM, Aaron France notifications@github.comwrote:

> If you could ask them how they're doing it, it'd be a massive help. If
> they're using the API then they must have some faith in the stability in
> it. If not, then it means that I can't reliably provide a service for that
> and thus am able to have runtime checks of the images. Which is also fine.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/AeroNotix/hpcloud/issues/1#issuecomment-19130356
> .

## 

http://technosophos.com
http://querypath.org
