### ISSUE TITLE
Implement new endpoints for ObjectStore

### ISSUE THREAD

**Issue by AeroNotix** [AeroNotix/hpcloud#5]
There have been two interesting additions to the ObjectStore API.
# Bulk Delete

Provide a newline delimited list of UTF-8 URL-Encoded filenames to delete. Seems useful and pretty easy to implement. Take a []string and encode it en masse.
# Auto Archive Extraction

Now this is simply a superb idea. You can upload a {tar,tar.bz,tar.bz2} file and the endpoint will automatically extract and create the containers when needed.

I think it'd be good to provide various functions for this:

func (a Access) Upload{tar,tar.bz,tar.bz2}(fpath string) error
func (a Access) Upload{tar,tar.bz,tar.bz2}FromFile(file io.Reader) error
func (a Access) Upload{tar,tar.bz,tar.bz2}FromPaths(paths []string) error

/cc @technosophos @mattfarina

**Comment by technosophos** [comment]
I totally agree. The upload feature would be a fantastic improvement. Bulk delete would be pretty useful too.

**Comment by AeroNotix** [comment]
Feel free to implement this if you have time, otherwise I'll get to it this week.
